### ISSUE TITLE
PAP green   PAP yellow

### ISSUE THREAD

**Issue by stappersg** [brunoooost/payloads_flipperZero#7]
What means `PAP` in overview table?

Which information is in the color?

**Comment by bst04** [comment]
Is **Plug And Play**, look:

**Green:** You don't need to change anything just pluged and it will work
**Orange:** You must change something like a webhook or sth else
**Red:** Don't Work or in Progress

**Comment by stappersg** [comment]
On Fri, Dec 13, 2024 at 12:24:44PM -0800, bst04 wrote:
> Closed #7 as completed.

#8
